<a href="https://colab.research.google.com/github/victortizs/Py-bootcamp/blob/main/DFs_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import pandas as pd
import numpy as np

In [ ]:
df1 = pd.DataFrame(np.random.randn(4, 6), columns=list('ABCDEF'))
df1

A         B         C         D         E         F
0  1.217468  0.950091 -1.692497 -0.287020  1.154518 -0.443057
1 -1.790402 -1.098956 -0.584154  0.592657 -0.866662  0.181188
2 -0.460630  0.491115  0.499371  0.934097  0.543696 -0.224705
3  0.393404  1.972029  0.169981 -0.022062  0.585966 -0.327843

In [ ]:
df2 = pd.DataFrame({"A": range(5), "B": range(5, 10)}, index=range(10, 15))
df2

A  B
10  0  5
11  1  6
12  2  7
13  3  8
14  4  9

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
print("Ingresa la ruta correspondiente al periodo 't' (más actual):")
ruta_b = input()
print("\nAhora la correspondiente al periodo 't-1' (anterior a 't'):")
ruta_a = input()

Ingresa la ruta correspondiente al periodo 't' (más actual):
/content/drive/MyDrive/4_Python/1_Sandbox/1_Taranto/CUV Articulos por division 202202.xlsx

Ahora la correspondiente al periodo 't-1' (anterior a 't'):
/content/drive/MyDrive/4_Python/1_Sandbox/1_Taranto/CUV Articulos por division 202201.xlsx


In [ ]:
df3 = pd.read_excel(ruta_b)
df3.rename(str.lower, axis="columns", inplace=True)

df4 = pd.read_excel(ruta_a)
df4.rename(str.lower, axis="columns", inplace=True)

In [ ]:
test_b = df3.loc[df3["division"] == "estampado"]
test_b["vigencia_cuv"] = test_b["vigencia_cuv"].apply(lambda j: j.date())
test_b.head()

<ipython-input-155-4e0f185769ca>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_b["vigencia_cuv"] = test_b["vigencia_cuv"].apply(lambda j: j.date())


codigo  cuv_usd vigencia_cuv  segundos   division
7          13385712   0.1689   2022-02-09     10.43  estampado
8     18350KPE9011N   1.3551   2022-02-09    224.16  estampado
9      31501KVSF001   0.4789   2022-02-09     31.29  estampado
10  45461KRH9000PLA   0.1403   2022-02-09     12.64  estampado
11    45462KPE7302N   0.2244   2022-02-09     32.14  estampado

In [ ]:
print(df3.iloc[df3.groupby("division")["cuv_usd"].agg(pd.Series.idxmax)]) # transform("max") instead of agg
print("\n", test_b.sort_values(by=["cuv_usd"], ascending=False).drop_duplicates(subset="division", keep="first"))
print("\n", df3[df3["division"] == "estampado"].sort_values("cuv_usd").drop_duplicates("division", keep="last"))
print("\n", df3["cuv_usd"][df3["division"] == "estampado"].max())

              codigo     cuv_usd vigencia_cuv  segundos    division
5         CDM2601000   25.991800   2016-01-29    755.17  cajas dir.
18     50615KPE7300N    3.675600   2022-02-14    111.14   estampado
469        OCH0195CL   28.732200   2022-02-18     60.00    fijacion
774          1476203   18.987000   2019-12-27    162.24       forja
1108        EK302300  158.002500   2022-02-18    180.00    friccion
1293  02J31124300S01    0.445100   2021-11-05    101.13  mecanizado
1297       BD13897-F    0.227100   2021-01-05     20.04     rotulas
2441        CG751-BL  305.676602   2022-02-09   3780.00         s/d
9817        801000-R  138.586000   2022-02-18    360.00     sellado

            codigo  cuv_usd vigencia_cuv  segundos   division
18  50615KPE7300N   3.6756   2022-02-14    111.14  estampado

            codigo  cuv_usd vigencia_cuv  segundos   division
18  50615KPE7300N   3.6756   2022-02-14    111.14  estampado

 3.6756


In [ ]:
pip install xlsxwriter

In [ ]:
# The enumerate () method adds a counter to an iterable and returns it in the form of an enumerating object.
# This enumerated object can then be used directly for loops or converted into a list of tuples using the list() function.
# Parameters:
# Iterable: any object that supports iteration
# Start: the index value from which the counter is to be started, by default it is 0

y = ["casa", "sol"]
print(type(enumerate(y)))
print(list(enumerate(y)))
print(list(enumerate(y, 100)), "\n")

for ele in y:
  print(ele)

print("\n")

for ele in enumerate(y):
  print(ele)

for count, ele in enumerate(y):
  print("\n", count, ele) # separately
  print(count)
  print(ele)

<class 'enumerate'>
[(0, 'casa'), (1, 'sol')]
[(100, 'casa'), (101, 'sol')] 

casa
sol


(0, 'casa')
(1, 'sol')

 0 casa
0
casa

 1 sol
1
sol


In [ ]:
nota_b = "Las columnas con el sufijo '_b' muestran datos vigentes al periodo " + ruta_b[-11:-7] + "-" + ruta_b[-7:-4]
nota_a = "\nLas columnas con el sufijo '_a' muestran datos vigentes al periodo " + ruta_a[-11:-7] + "-" + ruta_a[-7:-4]
print(nota_b, nota_a, "\n")
nota_inicial = nota_b + " " + nota_a
print(nota_inicial)

Las columnas con el sufijo '_b' muestran datos vigentes al periodo 2022-02. 
Las columnas con el sufijo '_a' muestran datos vigentes al periodo 2022-01. 

Las columnas con el sufijo '_b' muestran datos vigentes al periodo 2022-02. 
Las columnas con el sufijo '_a' muestran datos vigentes al periodo 2022-01.


In [ ]:
# import openpylx styles
# (font, alignment) (center, wrap, italic)

In [ ]:
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font

In [ ]:
test_c = test_b

with pd.ExcelWriter("/content/drive/MyDrive/4_Python/1_Sandbox/1_Taranto/prueba_z.xlsx") as writer1:
  test_c.to_excel(writer1, sheet_name="Ojo", freeze_panes=(4,0), index=False, startrow=3)
  wb1 = writer1.book
  ws1 = writer1.sheets["Ojo"]
  # ws1.write("A1", nota_inicial) # funciona
# ver letra más grande y colores en sufijos y fechas
  merge_format = wb1.add_format(
    {
        "bold": 0,
        "italic": 1,
    }
  )

  bold = wb1.add_format({"bold": True})
  italic = wb1.add_format({"italic": True})
  red = wb1.add_format({"color": "red"})
  blue = wb1.add_format({"color": "blue"})
  font_size = wb1.add_format({'font_size': 12})

  for n, col in enumerate(test_b.columns):


  ws1.write_rich_string("A1","Las columnas con el sufijo", red, " '_b'", " muestran datos vigentes al periodo ", red, ruta_b[-11:-7], red, "-", red, ruta_b[-7:-5], ".")
  ws1.write_rich_string("A2","Las columnas con el sufijo", blue, " '_a'", " muestran datos vigentes al periodo ", blue, ruta_a[-11:-7], blue, "-", blue, ruta_a[-7:-5], ".")
  # ws1.merge_range("A1:O1", nota_inicial, merge_format)
  writer1.save()

<ipython-input-162-f6f74570b1b2>:25: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer1.save()
/usr/local/lib/python3.10/dist-packages/xlsxwriter/workbook.py:368: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")


In [ ]:
ruta_exp = "/content/drive/MyDrive/4_Python/1_Sandbox/1_Taranto/" + "CUV_" + ruta_b[-11:-5] + "_vs_" + ruta_a[-11:-5] + "_test" + ".xlsx"
engine_exp = "xlsxwriter"

writer = pd.ExcelWriter(ruta_exp, engine=engine_exp)
test_b.style.set_properties(**{"text-align":"center"}).to_excel(writer, sheet_name="Hoja1", index=False, freeze_panes=(2, 0), startrow=1)

wb = writer.book
ws = writer.sheets["Hoja1"]

for i, col in enumerate(test_b.columns):
  # width = max(test_b[col].apply(lambda x: len(str(x))), len(col)) + 1 # (max len registro de col x, len encabezado col x + 1)
  width = max(test_b[col].apply(lambda x: len(str(x))).max(), len(col)) + 1 #, len(col)) + 1
  print(width)
  print(" ", i)
  ws.set_column(i, i, width=width)
writer.save()

16
  0
8
  1
13
  2
9
  3
10
  4


<ipython-input-163-e02fab3305a1>:16: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()


In [ ]:
# for i, col in enumerate(comparar_3.columns):
  # width = max(comparar_3[col].apply(lambda x: len(str(x))).max(), len(col)) + 1
  # worksheet.set_column(i, i, width)

In [ ]:
x = 0
for i in test_b.columns:
  x += 1
  print(x)

print(f"\n{x}")
print(f"\n{max(range(5))}")

1
2
3
4
5

5

4


In [ ]:
# string[start:stop:step]
string = "hola amigue"
print(string[::-1])
print(string[::2])

eugima aloh
hl mge


# Matrices



In [ ]:
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print("Matrix:")
print(matrix)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
def create_matrix_alfa(rows, cols, value=0):
    return [[value for _ in range(cols)] for _ in range(rows)]

def is_matrix_alfa(matrix_alfa):
    if not matrix_alfa or not isinstance(matrix_alfa, list) or not all(isinstance(row, list) for row in matrix_alfa):
        return False
    row_length = len(matrix_alfa[0])
    return all(len(row) == row_length for row in matrix_alfa)

matrix_alfa = create_matrix_alfa(3, 4)
print("matrix_alfa:", matrix_alfa)
print("Is this a matrix_alfa?", is_matrix_alfa(matrix_alfa))

matrix_alfa: [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
Is this a matrix_alfa? True
